language: node_js
node_js:
  - 9
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm test
deploy:
  local_dir: build
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
